// <auto-generated />
using System;
using Backend2Torneios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend2Torneios.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217141636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend2Torneios.Models.Comentario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<string>("JogadorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jogador_id");

                    b.Property<string>("PartidaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partida_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.ToTable("comentarios");
                });

            modelBuilder.Entity("Backend2Torneios.Models.Palpite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataPalpite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_palpite");

                    b.Property<string>("JogadorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jogador_id");

                    b.Property<string>("PartidaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("partida_id");

                    b.Property<int>("PlacarMandante")
                        .HasColumnType("integer")
                        .HasColumnName("placar_mandante");

                    b.Property<int>("PlacarVisitante")
                        .HasColumnType("integer")
                        .HasColumnName("placar_visitante");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId", "JogadorId")
                        .IsUnique();

                    b.ToTable("palpites");
                });
#pragma warning restore 612, 618
        }
    }
}
